name: Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build plugin
        run: npm run build
        
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir ${{ github.workspace }}/release
          cp main.js manifest.json README.md ${{ github.workspace }}/release
          if [ -f styles.css ]; then
            cp styles.css ${{ github.workspace }}/release
          fi
          cd ${{ github.workspace }}/release
          zip -r jwpub-bible-verses-${{ github.ref_name }}.zip .
          
      - name: Upload release artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: ${{ github.workspace }}/release
          
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          files: |
            ${{ github.workspace }}/release/main.js
            ${{ github.workspace }}/release/manifest.json
            ${{ github.workspace }}/release/README.md
            ${{ github.workspace }}/release/jwpub-bible-verses-${{ github.ref_name }}.zip
            ${{ github.workspace }}/release/styles.css 